### ISSUE TITLE
Copy full path (current: parent, wanted: parent+child)

### ISSUE THREAD

**Issue by PierreGUI** [ricardoemerson/yaml-path-copy#3]
Nice plugin already, saves plenty of time :)
Would be great to copy full path to the currently selected yaml key, with a different shortcut maybe ?
Thanks

**Comment by ricardoemerson** [comment]
Hello @PierreGUI, thank you for your suggestion and inform you that I have done the correction suggested by you.

Please check if worked as expected.

**Comment by PierreGUI** [comment]
Wow thanks, It's awesome !!
So far works great 💃
