### ISSUE TITLE
Copy path won't work before I display path first

### ISSUE THREAD

**Issue by PierreGUI** [ricardoemerson/yaml-path-copy#4]
Actually found a bug since last update, as title states.
Reproduce:
- Open yaml file in Atom (mean open atom)
- Try copy path (via shortcut or contextual menu). _Nothing happens_
- Try display path. _Works_
- Try copy again. _Works_

Not a blocker but clearly not an expected behaviour ;)
Cheers

**Comment by ricardoemerson** [comment]
Hey @PierreGUI, thanks again for your feedback about use of this package.

I located the issue and now is ok.
